### ISSUE TITLE
xls-admin 任务创建-添加试卷，查询不到试卷

### ISSUE THREAD

**Issue by SummerWindL** [mindskip/xzs#108]
直接上代码吧，你这个地方写的是6，但我看数据库设计没有6这个枚举

<img width="1097" alt="image" src="https://user-images.githubusercontent.com/24834548/115418043-b9d57680-a22b-11eb-9632-3601818bfb35.png">

![1618930548577](https://user-images.githubusercontent.com/24834548/115417893-990d2100-a22b-11eb-91dd-81e546d254df.jpg)

我直接改成了1固定试卷，按理说这边应该有个类型选择，如果没有默认查全部才对。

**Comment by alvis-u** [comment]
![image](https://user-images.githubusercontent.com/70456620/115482944-66424780-a282-11eb-9592-c9eba4c6572c.png)
