### ISSUE TITLE
docker方式部署后，显示系统内部错误

### ISSUE THREAD

**Issue by InfraBackend** [mindskip/xzs#490]
<img width="1315" alt="image" src="https://user-images.githubusercontent.com/42115674/224981555-46759123-b744-43fa-9850-b4300e1e1f44.png">
请问是什么原因，错误日志在哪看呢

**Comment by alvis-u** [comment]
日志在/usr/log/xzs下面，一般是数据库问题。

**Comment by InfraBackend** [comment]
这个咋改，也没找到配置文件在哪
