### ISSUE TITLE
使用docker部署，启动后一段时间内登录没问题，过几天就一直登录不上，显示登录超时

### ISSUE THREAD

**Issue by InfraBackend** [mindskip/xzs#492]
如题，是为什么呢，也没有看到错误
<img width="831" alt="image" src="https://github.com/mindskip/xzs/assets/42115674/30ff96b6-200a-42ae-8231-0982e50911f5">

**Comment by InfraBackend** [comment]
我发现了，是docker内部mysql自动关闭了，为什么会被关闭呢

**Comment by mindskip** [comment]
可以看看新版docker教程：https://www.mindskip.net:999/guide/deploy.html#_6-3-docker%E9%83%A8%E7%BD%B2
